### ISSUE TITLE
Retrieving executed commands from shell history

### ISSUE THREAD

**Issue by satyamsharma** [luo-anthony/DeveloperGPT#6]
After executing a command using developerGPT, I would want to see it behave as if I had manually written and executed it myself.

Specifically, I would prefer to have the executed (generated) commands entered in .zsh_history/.bash_history as well so that they show up when I type `history` in my terminal or when I perform reverse-lookup (aka bck-i-search) using `Ctrl+r`

This will make it more convenient to reuse and recall already executed commands (with slight changes for subsequent use cases) without invoking developerGPT and reentering the prompt, and incurring the usage on the API again

**Comment by luo-anthony** [comment]
Great Idea! Will work on this for the next release!

**Comment by luo-anthony** [comment]
Since there are multiple different shell varieties / shell history configurations (not possible to support them all, odd behavior with certain shell configurations), I thought an adequate solution to this is to copy the commands to the users clipboard automatically after executing the commands (supports Linux, Mac, and Windows)
